'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CarteraPSE.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set @Valor =
        '''(
        '''	Select Sum(LineTotal) As Total from 
        '''		(
        '''			Select LineTotal,
        '''			T1.Cadena1 + Cast(T0.TipoLin As Char(40)) + Cast(UPPER(T0.ItemName) as Char(80)) + &apos;0&apos; + Cast(Convert(VARCHAR(8), @FechaArchivo, 112) As char(8)) +
        '''			REPLICATE(&apos;0&apos;, 18 - DATALENGTH(Replace(Cast(T0.LineTotal as numeric(16,2)),&apos;.&apos;,&apos;&apos;))) + Replace(Cast(T0.LineTotal as numeric(16,2)),&apos;.&apos;,&apos;&apos;) +
        '''			T1.Cadena2 As &apos;Cadena&apos;, T0.Alumno, T0.Orden
        '''			From (
        '''
        '''			Select ItemName, Round(Sum(LineTotal),0) LineTotal, Alumno, &apos;00&apos; As  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CajaSocial() As String
            Get
                Return ResourceManager.GetString("CajaSocial", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set @Valor =
        '''(
        '''	Select Sum(LineTotal) As Total from 
        '''		(
        '''			Select LineTotal,
        '''			T1.Cadena1 + Cast(T0.TipoLin As Char(40)) + Cast(UPPER(T0.ItemName) as Char(80)) + &apos;0&apos; + Cast(Convert(VARCHAR(8), @FechaArchivo, 112) As char(8)) +
        '''			REPLICATE(&apos;0&apos;, 18 - DATALENGTH(Replace(Cast(T0.LineTotal as numeric(16,2)),&apos;.&apos;,&apos;&apos;))) + Replace(Cast(T0.LineTotal as numeric(16,2)),&apos;.&apos;,&apos;&apos;) +
        '''			T1.Cadena2 As &apos;Cadena&apos;, T0.Alumno, T0.Orden
        '''			From (
        '''
        '''			Select ItemName, Round(Sum(LineTotal),0) LineTotal, Alumno, &apos;00&apos; As  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CarteraPSE() As String
            Get
                Return ResourceManager.GetString("CarteraPSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set @Valor =
        '''(
        '''	Select Sum(Valor) As Total from 
        '''		(
        '''			Select
        '''			&apos;2&apos; +
        '''			REPLICATE(&apos;0&apos;, 35 - Len(IsNull(A3.U_EtyCode,&apos;&apos;))) + IsNull(A3.U_EtyCode,&apos;&apos;) + 
        '''			REPLICATE(&apos;0&apos;, 35 - Len(IsNull(A10.Name,&apos;&apos;))) + IsNull(A10.Name,&apos;&apos;) + 
        '''			CASE WHEN CHARINDEX(&apos;-&apos;, A2.LicTradNum) &gt; 0 THEN Cast(LEFT(A2.LicTradNum, CHARINDEX(&apos;-&apos;, A2.LicTradNum)-1) As char(80)) ELSE Cast(A2.LicTradNum As char(80)) END +
        '''			Cast(A0.DocEntry As char(80)) +
        '''			Cast(IsNull(A0.NumAtCard,&apos;&apos;) As Char(80)) +
        '''			Cast(&apos;00&apos; As Char(40)) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CarteraPSE1() As String
            Get
                Return ResourceManager.GetString("CarteraPSE1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select &apos;CDU026NUMO&apos;As &apos;NO TOCAR&apos;,&apos;CDU026NIDE&apos; As &apos;NO TOCAR&apos;,&apos;CDU026NCLI&apos;As &apos;NO TOCAR&apos;,&apos;CDU026TICC&apos; As &apos;NO TOCAR&apos;,&apos;CDU026NRCC&apos; As &apos;NO TOCAR&apos;,
        '''&apos;CDU026NITB&apos;As &apos;NIT DEL CLIENTE RECEPTOR&apos;,&apos;CDU026NOMB&apos; As &apos;NOMBRE DEL CLIENTE RECEPTOR&apos;,&apos;CDU026BANB&apos; As &apos;CODIGO BANCO&apos;,
        '''&apos;CDU026TIPC&apos; As &apos;1= CTA CTE / 2= CTA AHOR&apos;,&apos;CDU026NRCB&apos; As &apos;NUMERO DE CUENTA&apos;,&apos;CDU026CLAM&apos; As &apos;NO TOCAR&apos;,&apos;CDU026VLRB&apos; As &apos;VALOR SIN DECIMALES&apos;
        '''Union All
        '''Select
        '''Cast(Row_number() over (ORDER BY A2.LicTradNum) As nvarchar(40)) As &apos;NO TOCAR&apos;,
        '''&apos;&apos; As [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CDT() As String
            Get
                Return ResourceManager.GetString("CDT", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select &apos;CDU026NUMO&apos;As &apos;NO TOCAR&apos;,&apos;CDU026NIDE&apos; As &apos;NO TOCAR&apos;,&apos;CDU026NCLI&apos;As &apos;NO TOCAR&apos;,&apos;CDU026TICC&apos; As &apos;NO TOCAR&apos;,&apos;CDU026NRCC&apos; As &apos;NO TOCAR&apos;,
        '''&apos;CDU026NITB&apos;As &apos;NIT DEL CLIENTE RECEPTOR&apos;,&apos;CDU026NOMB&apos; As &apos;NOMBRE DEL CLIENTE RECEPTOR&apos;,&apos;CDU026BANB&apos; As &apos;CODIGO BANCO&apos;,
        '''&apos;CDU026TIPC&apos; As &apos;1= CTA CTE / 2= CTA AHOR&apos;,&apos;CDU026NRCB&apos; As &apos;NUMERO DE CUENTA&apos;,&apos;CDU026CLAM&apos; As &apos;NO TOCAR&apos;,&apos;CDU026VLRB&apos; As &apos;VALOR SIN DECIMALES&apos;
        '''Union All
        '''Select
        '''Cast(Row_number() over (ORDER BY A2.LicTradNum) As nvarchar(40)) As &apos;NO TOCAR&apos;,
        '''&apos;&apos; As [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property CDT2() As String
            Get
                Return ResourceManager.GetString("CDT2", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set @Conteo =
        '''(
        '''	Select C0.Filas From 
        '''	(
        '''		Select Count(*) As Filas from 
        '''		(
        '''			Select
        '''			REPLICATE(&apos;0&apos;, 5 - Len(Cast(Row_number() over (ORDER BY A1.DocEntry) + 1 As nvarchar(40)))) + Cast(Row_number() over (ORDER BY A1.DocEntry) + 1 As nvarchar(40)) As REGISTRO,
        '''			&apos;02&apos; As TIPO_REGISTRO,
        '''			REPLICATE(&apos;0&apos;, 12 - Len(IsNull(Cast(A2.DflAccount As Nvarchar(500)),&apos;0&apos;))) + IsNull(Cast(A2.DflAccount As Nvarchar(500)),&apos;0&apos;) As NUMERO_CUENTA,
        '''			REPLICATE(&apos;0&apos;, 11 - Len(Replace(IsNull(A2.LicTradNum,&apos;&apos;), &apos;- [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Colpatria() As String
            Get
                Return ResourceManager.GetString("Colpatria", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select * from (
        '''Select
        '''CASE WHEN CHARINDEX(&apos;-&apos;, A2.LicTradNum) &gt; 0 THEN Cast(LEFT(A2.LicTradNum, CHARINDEX(&apos;-&apos;, A2.LicTradNum)-1) As char(80)) ELSE Cast(A2.LicTradNum As char(80)) END +
        '''&apos;01&apos; +
        '''Cast(IsNull(A0.NumAtCard,&apos;&apos;) As Char(35)) +
        '''&apos;00&apos; +
        '''Cast(UPPER(Replace(Replace(Replace(Replace(Replace(Replace(IsNull(A0.CardName,&apos;&apos;),&apos;ñ&apos;,&apos;n&apos;), &apos;á&apos;, &apos;a&apos;), &apos;é&apos;,&apos;e&apos;), &apos;í&apos;, &apos;i&apos;), &apos;ó&apos;, &apos;o&apos;), &apos;ú&apos;,&apos;u &apos;) ) as Char(50)) +
        '''Space(50) As Cadena
        '''From OINV A0
        '''Inner Join INV1 A1 On A0.DocEntry = A1.DocEntry
        '''Inner Join OCRD [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UsuariosPSE() As String
            Get
                Return ResourceManager.GetString("UsuariosPSE", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select * from (
        '''Select
        '''CASE WHEN CHARINDEX(&apos;-&apos;, A2.LicTradNum) &gt; 0 THEN Cast(LEFT(A2.LicTradNum, CHARINDEX(&apos;-&apos;, A2.LicTradNum)-1) As char(80)) ELSE Cast(A2.LicTradNum As char(80)) END +
        '''&apos;01&apos; +
        '''Cast(IsNull(A0.NumAtCard,&apos;&apos;) As Char(35)) +
        '''&apos;00&apos; +
        '''Cast(UPPER(Replace(Replace(Replace(Replace(Replace(Replace(IsNull(A0.CardName,&apos;&apos;),&apos;ñ&apos;,&apos;n&apos;), &apos;á&apos;, &apos;a&apos;), &apos;é&apos;,&apos;e&apos;), &apos;í&apos;, &apos;i&apos;), &apos;ó&apos;, &apos;o&apos;), &apos;ú&apos;,&apos;u &apos;) ) as Char(50)) +
        '''Space(50) As Cadena
        '''From ORDR A0
        '''Inner Join RDR1 A1 ON A0.DocEntry = A1.DocEntry
        '''Inner Join OCRD [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property UsuariosPSE1() As String
            Get
                Return ResourceManager.GetString("UsuariosPSE1", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
